// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVOwyc_RYOF1cu0wgOWkuDgi80Fa-jvpU',
    appId: '1:75883876210:web:d30297a8f92695ce8857eb',
    messagingSenderId: '75883876210',
    projectId: 'flutter-chat-90b0f',
    authDomain: 'flutter-chat-90b0f.firebaseapp.com',
    storageBucket: 'flutter-chat-90b0f.appspot.com',
    measurementId: 'G-1SQWD2L0YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqq_961h35FDveocL3zOQpTw-n1YiiRxs',
    appId: '1:75883876210:android:96bb0da9ffcc00bc8857eb',
    messagingSenderId: '75883876210',
    projectId: 'flutter-chat-90b0f',
    storageBucket: 'flutter-chat-90b0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA95GwtBLR5grXO5PeKgiVrbmKP0Jxi-wY',
    appId: '1:75883876210:ios:164401226e4390138857eb',
    messagingSenderId: '75883876210',
    projectId: 'flutter-chat-90b0f',
    storageBucket: 'flutter-chat-90b0f.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA95GwtBLR5grXO5PeKgiVrbmKP0Jxi-wY',
    appId: '1:75883876210:ios:164401226e4390138857eb',
    messagingSenderId: '75883876210',
    projectId: 'flutter-chat-90b0f',
    storageBucket: 'flutter-chat-90b0f.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVOwyc_RYOF1cu0wgOWkuDgi80Fa-jvpU',
    appId: '1:75883876210:web:f27a8d91cc3fad7c8857eb',
    messagingSenderId: '75883876210',
    projectId: 'flutter-chat-90b0f',
    authDomain: 'flutter-chat-90b0f.firebaseapp.com',
    storageBucket: 'flutter-chat-90b0f.appspot.com',
    measurementId: 'G-NNDRV5N9E8',
  );

}